dataset_folder: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/'
map_dir: 'GroundTruthDataset'
baseline_training_dir: 'TrainingDataset3'
DA2_training_dir: 'DA_illumination2'
DA2rot_training_dir: 'DA_illumination2_rotacion'
DA3_training_dir: 'DA_illumination3'
DA3rot_training_dir: 'DA_illumination3_rotacion'


global_test_dir: 'TestDataset'
cloudy_test_dir: 'TestCloudy'
night_test_dir: 'TestNight'
sunny_tes_dir: 'TestSunny'