map_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/GroundTruthDataset'
baseline_training_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/TrainingDataset3'
DA2_training_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/DA_illumination2'
DA2rot_training_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/DA_illumination2_rotacion'
DA3_training_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/DA_illumination3'
DA3rot_training_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/DA_illumination3_rotacion'


global_test_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/TestDataset'
cloudy_test_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/TestCloudy'
night_test_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/TestNight'
sunny_tes_dir: '/home/arvc/Juanjo/Datasets/SiameseFriburgo/TestSunny'